version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules  
    environment:
      - NODE_ENV=development
    command: |
     sh -c "npm install && npm run build && npm start"  
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  
    environment:
      - NODE_ENV=development
    command: |
      sh -c "npm install && npm run dev"  
volumes:
  backend_node_modules:  
  frontend_node_modules:  